# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 3, 9, 20, 29, 4, 976077, tzinfo=utc))),
                ('reminder', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='TL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notify.TaskList'),
        ),
    ]
