# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 22, 53, 13, 409704, tzinfo=utc)),
        ),
    ]
