# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0003_auto_20170310_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 10, 21, 6, 20, 720172, tzinfo=utc)),
        ),
    ]
