# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0005_auto_20170310_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 6, 3, 31, 354132, tzinfo=utc)),
        ),
    ]
