# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notify', '0007_auto_20170311_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 22, 54, 20, 822354, tzinfo=utc)),
        ),
    ]
